apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
    labels:
      run: echo
    name: echo
  spec:
    replicas: 3
    selector:
      matchLabels:
        run: echo
    template:
      metadata:
        labels:
          run: echo
      spec:
        containers:
        - image: belaban/jgrp
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1"
            limits: 
              memory: "1Gi"
              cpu: "1"
          name: echo
          command: ["echo.sh"]
          env:
            - name: jgroups.external_addr
              value: "master-0.vrigamon0527.lab.upshift.rdu2.redhat.com"
kind: List
metadata: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: echo
  labels:
    run: echo
spec:
  ports:
  - name: echo
    nodePort: 31000
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    run: echo
#  sessionAffinity: None
  sessionAffinity: ClientIP
  type: NodePort


